# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170303_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='classes',
        ),
        migrations.AddField(
            model_name='course',
            name='tutors',
            field=models.ManyToManyField(to='user.Tutor'),
        ),
    ]
