# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170322_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tutors',
            field=models.ManyToManyField(to='user.Student'),
        ),
    ]
