# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tutor_tutors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='tutors',
            new_name='students',
        ),
    ]
