# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170322_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subscribed',
            field=models.ManyToManyField(to='user.Student'),
        ),
    ]
