# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_course_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default='hi', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeachCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tutors', models.ManyToManyField(related_name='tutors', to='user.SiteProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='subscribed',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tutors',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='students',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.AddField(
            model_name='learncourse',
            name='students',
            field=models.ManyToManyField(related_name='student', to='user.SiteProfile'),
        ),
    ]
