# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20170425_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('students', models.ManyToManyField(related_name='student', to='user.SiteProfile')),
                ('tutors', models.ManyToManyField(related_name='tutors', to='user.SiteProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='learncourse',
            name='students',
        ),
        migrations.RemoveField(
            model_name='teachcourse',
            name='tutors',
        ),
        migrations.DeleteModel(
            name='LearnCourse',
        ),
        migrations.DeleteModel(
            name='TeachCourse',
        ),
    ]
