# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20170427_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
