# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20170427_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutors',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='user.Profile'),
        ),
    ]
