# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20170501_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Student', 'Student'), ('Tutor', 'Tutor')], default='Student', max_length=7),
        ),
    ]
